# GET http://localhost:4004/odata/v4/product/printhelloworld(input=%20'Hello')


# GET http://localhost:4004/odata/v4/product/addition(num1=10, num2=10)


# GET http://localhost:4004/rest/product/myfunction(category= 2)

# GET http://localhost:4004/odata/v4/product/agelimit(age=30)


GET http://localhost:4004/rest/product/checkEvenOdd(nums= 9)